### ISSUE TITLE
How to sign tx offline?

### ISSUE THREAD

**Issue by Wangmmx** [chainx-org/chainx.js-v2#1]
How do I sign offline? After upgrading to 2.0, many methods can not be found. Are there SDKs available for offline signatures?
like this:

https://github.com/chainx-org/ChainX/wiki/JS-SDK#%E7%A6%BB%E7%BA%BF%E7%AD%BE%E5%90%8D-websocket-%E7%89%88%E6%9C%AC

**Comment by aaurix** [comment]
https://github.com/polkadot-js/api/issues/1461

**Comment by Wangmmx** [comment]
Repeated question, my mistake
