### ISSUE TITLE
请问一下chainX-v2升级后的离线签名是如何完成的

### ISSUE THREAD

**Issue by Wangmmx** [chainx-org/chainx.js-v2#2]
chainX升级前的离线签名sdk文档中都能找到，包括webSocket连接方式和http连接方式，升级后chainX的依赖库发生了改变，用之前的方式会产生很多报错，包括方法不存在等等。利用polkadot离线签名的方式也会报错，构造交易体中的部分字段没有支持。

所以我想请问一下升级后如何实现离线签名构造交易广播的呢？有相关参考的库或者sdk文档吗？如果是文档还没有更新，那么请问有相关源码来参考吗？ 十分感谢！
（我提过一些相关的issue，重复的可以不用回复了）

**Comment by aaurix** [comment]
chainx 使用的是polkadot的sdk ，参考polkadot

https://polkadot.js.org/docs/

https://github.com/polkadot-js/api/issues/1461

**Comment by Wangmmx** [comment]
好的，这是波卡早期的离线版本，我去看看
